version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "8081:8081"
      - "8443:8443"
    links:
      - php:docker-php-fpm
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  php:
    image: php:7.2-fpm
    container_name: docker-php-fpm
    restart: unless-stopped
    volumes:
      - ./data/nginx/html:/usr/share/nginx/html
    expose:
      - "9000" #开放端口给容器，不对外开放
